package com.sdnu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public void setISBN(java.lang.String ISBN) {
		set("ISBN", ISBN);
	}

	public java.lang.String getISBN() {
		return get("ISBN");
	}

	public void set书名(java.lang.String 书名) {
		set("书名", 书名);
	}

	public java.lang.String get书名() {
		return get("书名");
	}

	public void set作者(java.lang.String 作者) {
		set("作者", 作者);
	}

	public java.lang.String get作者() {
		return get("作者");
	}

	public void set出版社(java.lang.String 出版社) {
		set("出版社", 出版社);
	}

	public java.lang.String get出版社() {
		return get("出版社");
	}

	public void set复本量(java.lang.Integer 复本量) {
		set("复本量", 复本量);
	}

	public java.lang.Integer get复本量() {
		return get("复本量");
	}

	public void set库存量(java.lang.Integer 库存量) {
		set("库存量", 库存量);
	}

	public java.lang.Integer get库存量() {
		return get("库存量");
	}

}
