package com.sdnu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookS<M extends BaseBookS<M>> extends Model<M> implements IBean {

	public void set图书ID(java.lang.String 图书ID) {
		set("图书ID", 图书ID);
	}

	public java.lang.String get图书ID() {
		return get("图书ID");
	}

	public void setISBN(java.lang.String ISBN) {
		set("ISBN", ISBN);
	}

	public java.lang.String getISBN() {
		return get("ISBN");
	}

	public void set是否借出(java.lang.Boolean 是否借出) {
		set("是否借出", 是否借出);
	}

	public java.lang.Boolean get是否借出() {
		return get("是否借出");
	}

}
