package com.sdnu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseADMIN<M extends BaseADMIN<M>> extends Model<M> implements IBean {

	public void set用户名(java.lang.String 用户名) {
		set("用户名", 用户名);
	}

	public java.lang.String get用户名() {
		return get("用户名");
	}

	public void set密码(java.lang.String 密码) {
		set("密码", 密码);
	}

	public java.lang.String get密码() {
		return get("密码");
	}

}
