package com.sdnu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysdiagrams<M extends BaseSysdiagrams<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPrincipalId(java.lang.Integer principalId) {
		set("principal_id", principalId);
	}

	public java.lang.Integer getPrincipalId() {
		return get("principal_id");
	}

	public void setDiagramId(java.lang.Integer diagramId) {
		set("diagram_id", diagramId);
	}

	public java.lang.Integer getDiagramId() {
		return get("diagram_id");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setDefinition(byte[] definition) {
		set("definition", definition);
	}

	public byte[] getDefinition() {
		return get("definition");
	}

}
