package com.sdnu.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ADMIN", "用户名", ADMIN.class);
		arp.addMapping("Book", "ISBN", Book.class);
		arp.addMapping("BookS", "图书ID", BookS.class);
		arp.addMapping("Lend", "图书ID", Lend.class);
		arp.addMapping("Reader", "借书证号", Reader.class);
		arp.addMapping("Rlend", "图书ID", Rlend.class);
		arp.addMapping("sysdiagrams", "diagram_id", Sysdiagrams.class);
	}
}

