package com.sdnu.common.model;

import com.sdnu.common.model.base.BaseADMIN;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ADMIN extends BaseADMIN<ADMIN> {
	public static final ADMIN dao = new ADMIN().dao();
}
