package com.sdnu.common.model;

import com.sdnu.common.model.base.BaseBookS;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookS extends BaseBookS<BookS> {
	public static final BookS dao = new BookS().dao();
}
