package com.sdnu.common.model;

import com.sdnu.common.model.base.BaseLend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lend extends BaseLend<Lend> {
	public static final Lend dao = new Lend().dao();
}
