package com.sdnu.common.model;

import com.sdnu.common.model.base.BaseReader;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reader extends BaseReader<Reader> {
	public static final Reader dao = new Reader().dao();
}
