package com.sdnu.common.model;

import com.sdnu.common.model.base.BaseRlend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rlend extends BaseRlend<Rlend> {
	public static final Rlend dao = new Rlend().dao();
}
