package com.sdnu.common.model;

import com.sdnu.common.model.base.BaseSysdiagrams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sysdiagrams extends BaseSysdiagrams<Sysdiagrams> {
	public static final Sysdiagrams dao = new Sysdiagrams().dao();
}
